version: '3.0'

services: 
  fastapi:
    build: .
    container_name: fastapi  
    external_links:
      - postgres_db:postgres_db
    volumes:
      - ./app:/app
    ports:
      - 8000:80
    depends_on:
      - postgres_db
      - elastic
    networks:
      - app_network

  postgres_db:
    image: postgres:15-alpine
    container_name: postgres_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_USER=fastapi_server
      - POSTGRES_PASSWORD=fastapi_server
      - POSTGRES_DB=documents_db
    networks:
      - app_network  
  elastic:
    image: "bitnami/elasticsearch:7" 
    container_name: elastic 
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - elastic-data:/usr/share/elasticsearch/data
    networks:
      - app_network

volumes:
  postgres_data:
  server:
  elastic-data:

networks:
  app_network:
    driver: bridge